algoritmo "semnome"
// Função :
// Autor :
// Data : 01/02/2020
// Seção de Declarações 
var
   n:inteiro
inicio
// Seção de Comandos
   Escreval("Digite um numero : ")
      escreval
   leia(n)
            escreval
   se (n % 2 = 1) entao
      escreval("O número ",n,", digitado é Impar")
            escreval
   senao
        escreval("O número ",n,", digitado é Par")
                    escreval
   fimse

fimalgoritmo
